INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'Os Opostos sempre se atraem', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/o1KfmIKXZb3zXYWFKWt31G3w8DI.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Blitz', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qjqmhhc7uLub22mhu4V6DjOBwXM.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Fora do Mapa', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qNAPgepJ4NHNA74ThVsxQEOUceJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Caras Malvados', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/syKg3OmdtSYmkA7nNdtPUYdSFGL.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Titanic', 'https://m.media-amazon.com/images/I/51mTtUGvUCL._AC_.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Blitz', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qjqmhhc7uLub22mhu4V6DjOBwXM.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Megalodon', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hES2eVAbVt08JJTqgu3jmI34Yxx.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'redenção', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/u9QD9ddSVeYJABMSqBwfqe0NmsJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Olhos Famintos', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4deKiUXWqyATIEKCBSjRxCOLvu0.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vício Frenético', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9AcjcR5qBVWPnVgtR5fCDU3HVhv.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O espelho', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5xAzE9cgbWWL2ZDD4YyWR1iINPK.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Entre Irmãos', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/buKRRR6Z6TztAuMUw7DUXCwn4hs.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Detenção', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/98Z8KZ7kVgU47k709OGvrfCRgIo.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Para maiores', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/xYBuGOIBtHZxvf4kTKXKdsrPieq.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Pagando Bem que Mal tem', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2gL5KB4GV51O6rH9HTeDGeTy0XX.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'redenção', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/u9QD9ddSVeYJABMSqBwfqe0NmsJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Boyka', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/i1fetl7jL48JUIUt2PZFlCA5Of.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem Aranha', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tX0o4AdHpidgniTWwfzK0dNTKrc.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Cavaleiro da Lua', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tkc7AVyUoG9VEeDvukN0TVqa24C.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'redenção', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/u9QD9ddSVeYJABMSqBwfqe0NmsJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Doutor Estranho', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hq2igFqb31fDqGotz8ZuUfwKgn8.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Os Opostos sempre se atraem', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/o1KfmIKXZb3zXYWFKWt31G3w8DI.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Caras Malvados', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/syKg3OmdtSYmkA7nNdtPUYdSFGL.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Fora do Mapa', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qNAPgepJ4NHNA74ThVsxQEOUceJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Trek', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iwIdajr5Y4zq2ibvq75VnDAJBr.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Caminho do Verão', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tqcSehEOf0mgaYRvyF9VHUPSZR0.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'redenção', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/u9QD9ddSVeYJABMSqBwfqe0NmsJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Doutor Estranho', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hq2igFqb31fDqGotz8ZuUfwKgn8.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Entre Irmãos', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/buKRRR6Z6TztAuMUw7DUXCwn4hs.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Blitz', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qjqmhhc7uLub22mhu4V6DjOBwXM.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);